import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    flex: 1,
    paddingHorizontal: 22,
    paddingVertical: 18,
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 160,
    backgroundColor: Colors.partyPink,
    opacity: 0.22,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    bottom: -140,
    left: -100,
    width: 280,
    height: 280,
    borderRadius: 180,
    backgroundColor: Colors.partyBlue,
    opacity: 0.2,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 56,
    marginBottom: 54,
  },
  logoText: {
    fontSize: 42,
    fontWeight: '900',
    color: Colors.primary,
    textShadowColor: Colors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
    letterSpacing: 3,
  },
  logoSubtext: {
    marginTop: 10,
    color: Colors.textSecondary,
    fontSize: 16,
    letterSpacing: 0.4,
  },
  menuContainer: {
    gap: 16,
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    shadowColor: Colors.primary,
    shadowOpacity: 0.38,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryButtonText: {
    color: Colors.background,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  secondaryButtonText: {
    color: Colors.textSecondary,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 15,
  },
  sectionTitle: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 26,
    marginBottom: 8,
  },
  sectionSubtext: {
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    paddingVertical: 4,
  },
  backButtonText: {
    color: Colors.accent,
    fontWeight: '700',
    fontSize: 14,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  playerInput: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    color: Colors.text,
    fontSize: 16,
  },
  addButton: {
    backgroundColor: Colors.partyBlue,
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  addButtonText: {
    color: Colors.text,
    fontWeight: '800',
  },
  playersList: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 16,
    maxHeight: 270,
    gap: 10,
  },
  emptyPlayersText: {
    color: Colors.textMuted,
    textAlign: 'center',
    paddingVertical: 20,
  },
  playerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  playerName: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  removeButton: {
    backgroundColor: Colors.dangerSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  removeButtonText: {
    color: Colors.danger,
    fontWeight: '700',
    fontSize: 13,
  },
  disabledButton: {
    opacity: 0.45,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  roundInfo: {
    color: Colors.textSecondary,
    fontWeight: '700',
    fontSize: 13,
  },
  currentPlayerCard: {
    backgroundColor: Colors.partyPinkSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.partyPink,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  currentPlayerLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  currentPlayerName: {
    color: Colors.text,
    fontSize: 24,
    fontWeight: '800',
    marginTop: 2,
  },
  timerContainer: {
    alignItems: 'center',
    marginBottom: 14,
  },
  timerCircle: {
    width: 138,
    height: 138,
    borderRadius: 69,
    borderWidth: 4,
    borderColor: Colors.partyBlue,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.partyBlue,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 18,
    elevation: 12,
  },
  timerText: {
    color: Colors.text,
    fontWeight: '900',
    fontSize: 56,
  },
  timerLabel: {
    color: Colors.textSecondary,
    marginTop: 8,
    fontWeight: '700',
    letterSpacing: 1,
  },
  cardContainer: {
    marginBottom: 14,
  },
  card: {
    backgroundColor: Colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  cardLabel: {
    color: Colors.accent,
    fontWeight: '800',
    letterSpacing: 2,
    fontSize: 12,
    marginBottom: 8,
  },
  cardText: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 24,
    textAlign: 'center',
  },
  actionButton: {
    backgroundColor: Colors.success,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 14,
    shadowColor: Colors.success,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginBottom: 14,
  },
  explosionButton: {
    backgroundColor: Colors.warning,
    shadowColor: Colors.warning,
  },
  actionButtonText: {
    color: Colors.background,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 15,
  },
  scoreboardCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    gap: 8,
  },
  scoreboardTitle: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 16,
    marginBottom: 2,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scoreName: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  scoreValue: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 14,
  },
  leaderText: {
    marginTop: 6,
    color: Colors.accent,
    fontWeight: '700',
    fontSize: 13,
  },
});
