import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    flex: 1,
    paddingHorizontal: 22,
    paddingVertical: 18,
  },
  pengFlashOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FF3B30',
    zIndex: 20,
  },
  pengText: {
    position: 'absolute',
    top: '36%',
    alignSelf: 'center',
    color: '#FFF',
    fontSize: 48,
    fontWeight: '900',
    zIndex: 30,
    textShadowColor: '#7F1D1D',
    textShadowRadius: 12,
  },
  smokeText: {
    position: 'absolute',
    top: '47%',
    alignSelf: 'center',
    fontSize: 34,
    zIndex: 30,
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -120,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 160,
    backgroundColor: Colors.partyPink,
    opacity: 0.22,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    bottom: -140,
    left: -100,
    width: 280,
    height: 280,
    borderRadius: 180,
    backgroundColor: Colors.partyBlue,
    opacity: 0.2,
  },
  logoContainer: {
    alignItems: 'center',
    marginTop: 56,
    marginBottom: 54,
  },
  logoText: {
    fontSize: 42,
    fontWeight: '900',
    color: Colors.primary,
    textShadowColor: Colors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
    letterSpacing: 3,
  },
  logoSubtext: {
    marginTop: 10,
    color: Colors.textSecondary,
    fontSize: 16,
    letterSpacing: 0.4,
  },
  menuContainer: {
    gap: 16,
  },
  primaryButton: {
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 20,
    shadowColor: Colors.primary,
    shadowOpacity: 0.38,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryButtonText: {
    color: Colors.background,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 17,
  },
  secondaryButton: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  secondaryButtonText: {
    color: Colors.textSecondary,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 15,
  },
  sectionTitle: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 26,
    marginBottom: 8,
  },
  sectionSubtext: {
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  playerCountText: {
    color: Colors.accent,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
  },
  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 14,
    paddingVertical: 4,
  },
  backButtonText: {
    color: Colors.accent,
    fontWeight: '700',
    fontSize: 14,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    alignItems: 'stretch',
  },
  playerInput: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: Colors.partyBlue,
    paddingHorizontal: 16,
    minHeight: 60,
    color: Colors.text,
    fontSize: 19,
    fontWeight: '700',
  },
  addButton: {
    backgroundColor: Colors.partyBlue,
    borderRadius: 14,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  addButtonText: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 16,
  },
  playersList: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 16,
    maxHeight: 270,
    gap: 10,
  },
  emptyPlayersText: {
    color: Colors.textMuted,
    textAlign: 'center',
    paddingVertical: 20,
  },
  playerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  playerName: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  removeButton: {
    backgroundColor: Colors.dangerSoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  removeButtonText: {
    color: Colors.danger,
    fontWeight: '700',
    fontSize: 13,
  },
  disabledButton: {
    opacity: 0.45,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  roundInfo: {
    color: Colors.textSecondary,
    fontWeight: '700',
    fontSize: 13,
  },
  currentPlayerCard: {
    backgroundColor: Colors.partyPinkSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.partyPink,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  currentPlayerLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  currentPlayerName: {
    color: Colors.text,
    fontSize: 24,
    fontWeight: '800',
    marginTop: 2,
  },
  revolverCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    alignItems: 'center',
    marginBottom: 10,
  },
  revolverTitle: {
    color: Colors.textSecondary,
    fontSize: 12,
    letterSpacing: 1,
    fontWeight: '700',
    marginBottom: 4,
  },
  revolverAmmoText: {
    color: Colors.accent,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
  },
  revolverBody: {
    width: 170,
    height: 190,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chamberSpinLayer: {
    position: 'absolute',
  },
  cylinderMarkPrimary: {
    position: 'absolute',
    top: 8,
    left: 56,
    width: 8,
    height: 16,
    borderRadius: 3,
    backgroundColor: '#F59E0B',
  },
  chamberCircleBase: {
    position: 'absolute',
    top: 16,
    left: 25,
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 2,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
  },
  chamberDot: {
    position: 'absolute',
    top: 0,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chamberDotLoaded: {
    backgroundColor: '#C4892D',
    borderColor: '#F7D07A',
  },
  chamberDotSpent: {
    backgroundColor: Colors.card,
    borderColor: Colors.border,
  },
  chamberBulletCore: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#5F3A12',
  },
  revolverNeedle: {
    position: 'absolute',
    width: 4,
    height: 70,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  revolverNeedleHead: {
    width: 14,
    height: 28,
    borderRadius: 8,
    backgroundColor: Colors.primary,
  },
  revolverCenter: {
    position: 'absolute',
    top: 66,
    left: 75,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.accent,
  },
  activePointerWrap: {
    position: 'absolute',
    top: 6,
    left: 65,
    alignItems: 'center',
    width: 40,
  },
  activePointerText: {
    color: Colors.accent,
    fontSize: 26,
    fontWeight: '900',
  },
  activePointerName: {
    position: 'absolute',
    top: 150,
    width: 170,
    textAlign: 'center',
    color: Colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  timerBarWrap: {
    marginBottom: 12,
  },
  timerBarTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: Colors.card,
    overflow: 'hidden',
  },
  timerBarFill: {
    height: '100%',
    backgroundColor: Colors.warning,
  },
  questionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    marginBottom: 10,
  },
  questionLabel: {
    color: Colors.textSecondary,
    fontSize: 12,
    letterSpacing: 1,
    fontWeight: '700',
  },
  questionValue: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: '800',
    marginTop: 2,
  },
  questionPrompt: {
    color: Colors.accent,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 8,
  },
  validationText: {
    color: Colors.warning,
    fontWeight: '700',
    fontSize: 13,
    marginBottom: 10,
  },
  instructionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    gap: 6,
    marginBottom: 10,
  },
  instructionText: {
    color: Colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  actionButton: {
    backgroundColor: Colors.success,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 14,
    shadowColor: Colors.success,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginBottom: 14,
    flex: 1,
  },
  answerRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  correctButton: {
    backgroundColor: Colors.success,
    shadowColor: Colors.success,
  },
  explosionButton: {
    backgroundColor: Colors.warning,
    shadowColor: Colors.warning,
  },
  primaryButtonMini: {
    flex: 0,
    marginTop: 8,
  },
  actionButtonText: {
    color: Colors.background,
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 15,
  },
  rewardCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.accent,
    padding: 14,
    gap: 8,
    marginBottom: 12,
  },
  rewardTitle: {
    color: Colors.accent,
    fontWeight: '800',
    fontSize: 16,
  },
  rewardText: {
    color: Colors.textSecondary,
    fontSize: 14,
  },
  rewardTargetButton: {
    backgroundColor: Colors.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  rewardTargetText: {
    color: Colors.text,
    fontWeight: '700',
    textAlign: 'center',
  },
  resultMessageText: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  resultSubText: {
    color: Colors.textSecondary,
    fontSize: 13,
  },
  scoreboardCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 14,
    gap: 8,
  },
  scoreboardTitle: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 16,
    marginBottom: 2,
  },
  scoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scoreName: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  scoreValue: {
    color: Colors.text,
    fontWeight: '800',
    fontSize: 14,
  },
  leaderText: {
    marginTop: 6,
    color: Colors.accent,
    fontWeight: '700',
    fontSize: 13,
  },
});
